import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  caseStudiesSidebar: [{ type: 'autogenerated', dirName: 'case-studies' }],
};

export default sidebars;
